---

- name: Run federation SSO setup on reproducer
  hosts: "{{ cifmw_target_host | default('localhost') }}"
  gather_facts: true
  tasks:
    - name: Read uni vars from federation role
      ansible.builtin.import_role:
        name: federation
        vars_from: uni-vars.yml
    - debug:
        var: cifmw_federation_keycloak_url
